import type { Metadata } from "next";
import { Noto_Sans_JP, Inter, Playfair_Display } from "next/font/google";
import "./globals.css";

import Seo from "../components/Seo";
import { ThemeProvider } from "../context/ThemeProvider";
import { LanguageProvider } from "../context/LanguageProvider";

const notoSans = Noto_Sans_JP({
  weight: ["400", "700"],
  variable: "--font-noto-sans",
  subsets: ["latin"],
  display: "swap",
});

const inter = Inter({
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const playfair = Playfair_Display({
  weight: ["400", "500", "600", "700"],
  variable: "--font-playfair",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className={`${notoSans.variable} ${inter.variable} ${playfair.variable}`}>
        <ThemeProvider>
          <LanguageProvider>
            <div className="antialiased">
              <Seo />
              {children}
            </div>
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
